"""Self-contained HTML renderer for dashboard/CLI report artifacts (ADR-0201).

Follows the ADR-0131/0140 artifact contract established by ``trend/html.py``:
one file, no JavaScript, no external requests, chart(s) as inline SVG with
``CHART_CSS``, the data table, and the canonical JSON embedded in a
``<script type="application/json">`` block for machine consumption.

Row output is capped (default 5 000) with an explicit "showing first N of M"
line — never silent truncation (ADR-0199 rule 4).
"""
from __future__ import annotations

import json
from typing import Any

from jinja2 import Environment
from markupsafe import Markup

from novafabric.viz.svg import CHART_CSS

DEFAULT_ROW_CAP = 5_000

_TEMPLATE = (
    """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ page_title }}</title>
<style>
:root { color-scheme: light dark; }
body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 60rem;
       padding: 0 1rem; line-height: 1.5; }
h1 { font-size: 1.4rem; border-bottom: 2px solid currentColor; padding-bottom: .4rem; }
h2 { font-size: 1.1rem; margin-top: 2rem; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { border: 1px solid rgba(128,128,128,.5); padding: .35rem .6rem; text-align: left; }
th { background: rgba(128,128,128,.15); }
code { font-family: ui-monospace, monospace; font-size: .85em; }
.none { opacity: .65; font-style: italic; }
.notice { border: 1px solid rgba(128,128,128,.5); background: rgba(128,128,128,.1);
          padding: .6rem .8rem; margin: 1rem 0; font-size: .9rem; }
"""
    + CHART_CSS
    + """
footer { margin-top: 2.5rem; font-size: .8rem; opacity: .75; }
</style>
</head>
<body>
<h1>{{ page_title }}</h1>
<p class="notice">Offline report snapshot generated by NovaFabric — a
read-only artifact over local run data, <strong>not</strong> a live monitor.
NovaFabric produces evidence that supports compliance workflows; it does not
certify compliance.</p>

{% if filters %}<h2>Filters</h2>
<table>
{% for key, value in filters.items() %}<tr><th>{{ key }}</th>
<td><code>{{ value }}</code></td></tr>
{% endfor %}</table>
{% endif %}

{% if chart_svg %}<h2>{{ chart_title or "Chart" }}</h2>
{{ chart_svg }}
{% endif %}

<h2>Data ({{ shown_rows }} row{{ "s" if shown_rows != 1 }}{% if truncated %}
&#8212; showing first {{ shown_rows }} of {{ total_rows }}{% endif %})</h2>
{% if rows %}<table>
<tr>{% for c in columns %}<th>{{ c }}</th>{% endfor %}</tr>
{% for row in rows %}<tr>
{% for c in columns %}<td>{% if row[c] is not none %}{{ row[c] }}{% else %}<span
class="none">&#8212;</span>{% endif %}</td>{% endfor %}
</tr>
{% endfor %}</table>{% else %}<p class="none">no rows matched</p>{% endif %}

<footer>
Generated by {{ generator }} at {{ generated_at }} &#183; self-contained
offline page &#8212; the embedded canonical JSON is in the
<code>report-data</code> block below (View Source).
</footer>

<script type="application/json" id="report-data">
{{ report_json }}
</script>
</body>
</html>
"""
)


def render_report_html(
    *,
    title: str,
    columns: list[str],
    rows: list[dict[str, Any]],
    chart_svg: str | None = None,
    chart_title: str | None = None,
    filters: dict[str, str] | None = None,
    generated_at: str = "",
    generator: str = "nova serve",
    row_cap: int = DEFAULT_ROW_CAP,
) -> str:
    """Render a report as one self-contained HTML page."""
    total = len(rows)
    truncated = total > row_cap
    shown = rows[:row_cap]
    payload = {
        "title": title,
        "columns": columns,
        "rows": shown,
        "total_rows": total,
        "truncated": truncated,
        "filters": filters or {},
        "generated_at": generated_at,
        "generator": generator,
    }
    # JSON-escape "<" (u003c) so the embedded payload can never close the
    # <script> block early; it stays valid JSON. Same rule as trend/html.py.
    report_json = json.dumps(payload, ensure_ascii=False, default=str).replace(
        "<", "\\u003c"
    )
    env = Environment(autoescape=True)
    template = env.from_string(_TEMPLATE)
    return template.render(
        page_title=title,
        columns=columns,
        rows=shown,
        shown_rows=len(shown),
        total_rows=total,
        truncated=truncated,
        filters={k: v for k, v in (filters or {}).items() if v},
        chart_svg=Markup(chart_svg) if chart_svg else None,
        chart_title=chart_title,
        generated_at=generated_at,
        generator=generator,
        report_json=Markup(report_json),
    )
