"""Single-file offline HTML renderer for a ``CapsuleView`` (ADR-0140 P2).

Emits exactly **one** self-contained ``.html`` file satisfying the normative
contract of ``design/spec/capsule-viewer-v0.md`` Part 2:

- zero external requests — no CDN, fonts, images, scripts, ``fetch``/sockets;
- all CSS inline in ``<style>``; no JavaScript at all (no-JS static tables);
- the ``CapsuleView`` JSON embedded inline in
  ``<script type="application/json" id="capsule-view-data">`` for View-Source
  inspection;
- renders fully from ``file://`` with no server and no build toolchain.

The page is a human-readable *view*, not a cryptographic verifier (D4/D6):
it states plainly that real verification is ``nova verify`` / the signed
Evidence Bundle. Uses Jinja2 (existing Tier-A runtime dependency; ADR-0024).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jinja2 import Environment
from markupsafe import Markup

from novafabric.viewer.view import build_capsule_view

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ page_title }}</title>
<style>
:root { color-scheme: light dark; }
body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 60rem;
       padding: 0 1rem; line-height: 1.5; }
h1 { font-size: 1.4rem; border-bottom: 2px solid currentColor; padding-bottom: .4rem; }
h2 { font-size: 1.1rem; margin-top: 2rem; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { border: 1px solid rgba(128,128,128,.5); padding: .35rem .6rem; text-align: left; }
th { background: rgba(128,128,128,.15); }
code { font-family: ui-monospace, monospace; font-size: .85em; }
.none { opacity: .65; font-style: italic; }
.notice { border: 1px solid rgba(128,128,128,.5); background: rgba(128,128,128,.1);
          padding: .6rem .8rem; margin: 1rem 0; font-size: .9rem; }
footer { margin-top: 2.5rem; font-size: .8rem; opacity: .75; }
</style>
</head>
<body>
<h1>{{ page_title }}</h1>
<p class="notice">{{ view.notes }} This page is a human-readable summary rendered
offline from the capsule; it is <strong>not</strong> a cryptographic verifier and
<strong>not</strong> the signed Evidence Bundle.</p>

<h2>Capsule</h2>
<table>
<tr><th>Run ID</th><td><code>{{ view.capsule.run_id }}</code></td></tr>
<tr><th>Capture mode</th><td>{{ view.capsule.capture_mode }}</td></tr>
<tr><th>Started</th><td>{{ view.capsule.started_at }}</td></tr>
<tr><th>Finished</th><td>{{ view.capsule.finished_at }}</td></tr>
{% if view.capsule.agent_id is defined %}<tr><th>Agent</th>
<td><code>{{ view.capsule.agent_id }}</code></td></tr>
{% endif %}{% if view.capsule.capsule_hash is defined %}<tr><th>Capsule hash</th>
<td><code>{{ view.capsule.capsule_hash }}</code></td></tr>
{% endif %}</table>

<h2>Model calls ({{ view.model_calls | length }})</h2>
{% if view.model_calls %}<table>
<tr><th>ID</th><th>Model</th><th>Status</th>
<th>Input tokens</th><th>Output tokens</th><th>Latency (ms)</th></tr>
{% for c in view.model_calls %}<tr>
<td><code>{{ c.model_call_id }}</code></td>
<td>{{ c.model }}</td>
<td>{{ c.status }}</td>
<td>{{ c.input_tokens if c.input_tokens is not none else "—" }}</td>
<td>{{ c.output_tokens if c.output_tokens is not none else "—" }}</td>
<td>{{ c.latency_ms if c.latency_ms is not none else "—" }}</td>
</tr>
{% endfor %}</table>{% else %}<p class="none">none recorded</p>{% endif %}

<h2>Tool calls ({{ view.tool_calls | length }})</h2>
{% if view.tool_calls %}<table>
<tr><th>ID</th><th>Tool</th><th>Mutation class</th><th>Status</th><th>Duration (ms)</th></tr>
{% for c in view.tool_calls %}<tr>
<td><code>{{ c.tool_call_id }}</code></td>
<td>{{ c.tool_name }}</td>
<td>{{ c.mutation_class }}</td>
<td>{{ c.status }}</td>
<td>{{ c.duration_ms if c.duration_ms is not none else "—" }}</td>
</tr>
{% endfor %}</table>{% else %}<p class="none">none recorded</p>{% endif %}

<h2>Eval scores ({{ view.scores | length }})</h2>
{% if view.scores %}<table>
<tr><th>Suite / metric</th><th>Value</th></tr>
{% for s in view.scores %}<tr>
<td>{{ s.suite }}</td>
<td>{{ s.value if s.value is not none else "—" }}</td>
</tr>
{% endfor %}</table>{% else %}<p class="none">none recorded</p>{% endif %}

<h2>Lineage references</h2>
{% if view.lineage_refs.nodes %}<table>
<tr><th>From</th><th>Type</th><th>To</th></tr>
{% for e in view.lineage_refs.edges %}<tr>
<td><code>{{ e['from'] }}</code></td>
<td>{{ e.type }}</td>
<td><code>{{ e.to }}</code></td>
</tr>
{% endfor %}</table>
<p>Nodes:
{% for n in view.lineage_refs.nodes %}<code>{{ n }}</code>{{ ", " if not loop.last }}
{%- endfor %}</p>
{% else %}<p class="none">none recorded</p>{% endif %}

<footer>
Generated by {{ view.generator.name }} {{ view.generator.version }} at
{{ view.generated_at }} · CapsuleView schema {{ view.schema_version }} ·
self-contained offline page (ADR-0140) — the embedded summary data is in the
<code>capsule-view-data</code> block below (View Source).
</footer>

<script type="application/json" id="capsule-view-data">
{{ view_json }}
</script>
</body>
</html>
"""


def render_capsule_view_html(view: dict[str, Any]) -> str:
    """Render a ``CapsuleView`` dict as the self-contained HTML page."""
    env = Environment(autoescape=True)
    template = env.from_string(_TEMPLATE)
    page_title = view.get("title") or f"Capsule {view['capsule']['run_id']}"
    # JSON-escape every "<" (unicode escape u003c) so the embedded payload can
    # never close the <script> block early or introduce markup; it stays valid JSON.
    view_json = json.dumps(view, indent=2, ensure_ascii=False).replace("<", "\\u003c")
    return template.render(view=view, page_title=page_title, view_json=Markup(view_json))


def export_capsule_html(
    capsule_dir: str | Path,
    output: str | Path,
    *,
    title: str | None = None,
) -> tuple[Path, list[str]]:
    """Project *capsule_dir* and write the single self-contained HTML file.

    Returns ``(written_path, warnings)``; read-only on the capsule, never
    blocks on partially readable sections (ADR-0140 D6).
    """
    result = build_capsule_view(capsule_dir, title=title)
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_capsule_view_html(result.view), encoding="utf-8")
    return out_path, result.warnings
