/**
 * ADR-0239 evidence cart — the session store and the export panel.
 *
 * Store: references only, idempotent on (kind, ref), order preserved, kept in
 * sessionStorage (D7), every item stamped with added_at/added_from.
 * Panel: invisible while empty; every export outcome is legible — success,
 * per-item unresolved (with an explicit "record the omissions" path), and the
 * server's refusals (403 admin, 503 audit).
 */
import { act, fireEvent, render, renderHook, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const exportEvidenceCart = vi.fn();

vi.mock('@/lib/api', () => ({
  api: { exportEvidenceCart: (...a: unknown[]) => exportEvidenceCart(...a) },
}));

import EvidenceCartPanel from '@/components/dashboard/EvidenceCartPanel';
import { addEntry, removeEntry, useEvidenceCart } from '@/lib/evidenceCart';

const okResult = {
  ok: true, bundle_path: '/h/.novafabric/evidence/cart-x.zip', bundle_sha256: 'a'.repeat(64),
  size_bytes: 10, item_count: 2, capsule_count: 2, unresolved: [], contains_held_evidence: false,
  legal_holds: [], audit_entry_hash: 'b'.repeat(64), key_autogenerated: false,
  cli_verify: 'nova verify /h/.novafabric/evidence/cart-x.zip',
};

function seed(...ids: string[]) {
  sessionStorage.setItem('nova.evidenceCart.v1', JSON.stringify(
    ids.map(ref => ({ kind: 'run', ref, added_at: '2026-10-02T00:00:00Z', added_from: '/dashboard?tab=runs' })),
  ));
}

describe('evidence cart store', () => {
  beforeEach(() => { sessionStorage.clear(); window.history.replaceState({}, '', '/dashboard?tab=runs&f=status%3Aerror'); });

  it('is idempotent on (kind, ref) and preserves order', () => {
    const a = { kind: 'run' as const, ref: 'A', added_at: 't1' };
    const b = { kind: 'run' as const, ref: 'B', added_at: 't2' };
    const once = addEntry(addEntry([], a), b);
    expect(addEntry(once, { ...a, added_at: 't3' })).toBe(once);
    expect(once.map(e => e.ref)).toEqual(['A', 'B']);
    expect(removeEntry(once, 'run', 'A').map(e => e.ref)).toEqual(['B']);
  });

  it('persists to sessionStorage with the view it was added from', () => {
    const { result } = renderHook(() => useEvidenceCart());
    act(() => result.current.add('run', 'R1'));
    const stored = JSON.parse(sessionStorage.getItem('nova.evidenceCart.v1') ?? '[]');
    expect(stored).toHaveLength(1);
    expect(stored[0]).toMatchObject({ kind: 'run', ref: 'R1', added_from: '/dashboard?tab=runs&f=status%3Aerror' });
    expect(typeof stored[0].added_at).toBe('string');
    expect(localStorage.getItem('nova.evidenceCart.v1')).toBeNull();
    expect(result.current.has('run', 'R1')).toBe(true);
  });

  it('degrades to an empty cart on corrupt storage', () => {
    sessionStorage.setItem('nova.evidenceCart.v1', '{not json');
    const { result } = renderHook(() => useEvidenceCart());
    expect(result.current.items).toEqual([]);
  });
});

describe('EvidenceCartPanel', () => {
  beforeEach(() => { sessionStorage.clear(); exportEvidenceCart.mockReset(); });

  it('renders nothing while the cart is empty', () => {
    const { container } = render(<EvidenceCartPanel />);
    expect(container).toBeEmptyDOMElement();
  });

  it('exports after confirmation and shows the bundle and how to verify it', async () => {
    seed('A', 'B');
    exportEvidenceCart.mockResolvedValue(okResult);
    render(<EvidenceCartPanel />);
    fireEvent.click(screen.getByTestId('cart-export'));
    fireEvent.click(screen.getByRole('button', { name: 'Export' }));
    expect(await screen.findByTestId('cart-export-done')).toHaveTextContent('cart-x.zip');
    expect(screen.getByText(/nova verify/)).toBeInTheDocument();
    expect(exportEvidenceCart).toHaveBeenCalledWith(
      expect.arrayContaining([expect.objectContaining({ ref: 'A' })]),
      { accept_unresolved: false },
    );
  });

  it('lists unresolved items and only proceeds on an explicit omission choice', async () => {
    seed('A', 'B', 'GONE');
    exportEvidenceCart.mockResolvedValueOnce({
      ok: false, status: 409, error: 'unresolved_items', message: '409', remedy: 'remove them',
      unresolved: [{ kind: 'run', ref: 'GONE', unresolved_reason: 'run not found: GONE' }],
    }).mockResolvedValueOnce({ ...okResult, unresolved: [{ kind: 'run', ref: 'GONE' }] });
    render(<EvidenceCartPanel />);
    fireEvent.click(screen.getByTestId('cart-export'));
    fireEvent.click(screen.getByRole('button', { name: 'Export' }));
    const alert = await screen.findByTestId('cart-export-error');
    expect(alert).toHaveTextContent('1 reference(s) could not be resolved — nothing was exported.');
    expect(alert).toHaveTextContent('run not found: GONE');
    fireEvent.click(screen.getByRole('button', { name: /record the omissions/ }));
    await waitFor(() => expect(exportEvidenceCart).toHaveBeenLastCalledWith(expect.any(Array), { accept_unresolved: true }));
    expect(await screen.findByTestId('cart-export-done')).toHaveTextContent('1 omission(s) recorded');
  });

  it('explains an admin-scope refusal and an audit refusal', async () => {
    seed('A', 'B');
    exportEvidenceCart.mockResolvedValueOnce({
      ok: false, status: 403, error: null, message: "scope 'admin' required", remedy: null, unresolved: [],
    });
    render(<EvidenceCartPanel />);
    fireEvent.click(screen.getByTestId('cart-export'));
    fireEvent.click(screen.getByRole('button', { name: 'Export' }));
    expect(await screen.findByTestId('cart-export-error')).toHaveTextContent('admin-scoped credential');

    exportEvidenceCart.mockResolvedValueOnce({
      ok: false, status: 503, error: 'audit_unavailable', message: '503', remedy: 'make the audit log writable', unresolved: [],
    });
    fireEvent.click(screen.getByTestId('cart-export'));
    fireEvent.click(screen.getByRole('button', { name: 'Export' }));
    await waitFor(() => expect(screen.getByTestId('cart-export-error')).toHaveTextContent('no bundle was kept'));
    expect(screen.getByTestId('cart-export-error')).toHaveTextContent('make the audit log writable');
  });
});
