"""E-5: JanusGraph minimal deployment profile generator (Cassandra + JanusGraph)."""

from __future__ import annotations


def generate_janusgraph_minimal_profile(
    replication_factor: int = 3,
    janusgraph_tag: str = "1.1.0",
    cassandra_tag: str = "latest",
    novafabric_tag: str = "latest",
    image_tag: str | None = None,
) -> str:
    """Return a docker-compose YAML string for a 3-node JanusGraph minimal deployment.

    ``janusgraph_tag``, ``cassandra_tag``, and ``novafabric_tag`` are
    independently defaulted — the three images (``janusgraph/janusgraph``,
    ``cassandra``, ``novafabric/novafabric``) are unrelated projects with
    unrelated version schemes, so pinning one should never silently move the
    others.

    .. deprecated::
        ``image_tag`` is a backward-compatible alias retained for existing
        callers (e.g. ``nova lineage-store profile --image-tag``). When
        passed, it overrides all three of ``janusgraph_tag``,
        ``cassandra_tag``, and ``novafabric_tag`` to the same value — the
        legacy (buggy) behavior. Prefer the three per-image parameters.
    """
    if image_tag is not None:
        janusgraph_tag = cassandra_tag = novafabric_tag = image_tag
    return f"""\
# Generated by nova lineage-store profile --target janusgraph-minimal
# Cassandra replication factor: {replication_factor}

version: "3.9"

services:
  cassandra:
    image: cassandra:{cassandra_tag}
    environment:
      CASSANDRA_CLUSTER_NAME: nova-lineage-cluster
      CASSANDRA_DC: dc1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  janusgraph:
    image: janusgraph/janusgraph:{janusgraph_tag}
    environment:
      JAVA_OPTIONS: -Xmx4g
      janusgraph.storage.backend: cql
      janusgraph.storage.hostname: cassandra
      janusgraph.storage.cql.replication-factor: "{replication_factor}"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - janusgraph-data:/var/lib/janusgraph
    healthcheck:
      test: ["CMD-SHELL", "bin/gremlin.sh -e scripts/empty-sample.groovy"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    ports:
      - "8182:8182"
    restart: unless-stopped

  nova-lineage:
    image: novafabric/novafabric:{novafabric_tag}
    environment:
      NOVA_LINEAGE_BACKEND: janusgraph
      NOVA_JANUSGRAPH_URL: ws://janusgraph:8182/gremlin
    depends_on:
      janusgraph:
        condition: service_healthy
    restart: unless-stopped

volumes:
  cassandra-data:
    driver: local
  janusgraph-data:
    driver: local
"""
