"""E-4: KuzuDB vertical deployment profile generator."""

from __future__ import annotations


def generate_kuzudb_vertical_profile(
    node_size: str = "16g-ram-500g-nvme",
    image_tag: str = "latest",
) -> str:
    """Return a docker-compose YAML string for a KuzuDB vertical deployment."""
    return f"""\
# Generated by nova lineage-store profile --target kuzudb-vertical
# Gate condition: ship as production-primary when p99 depth-5 < 500ms at 10M edges (Phase 6 B-7)
# Node size profile: {node_size}

version: "3.9"

services:
  nova-lineage:
    image: novafabric/novafabric:{image_tag}
    environment:
      NOVA_LINEAGE_BACKEND: kuzudb
      NOVA_KUZU_DB_PATH: /data/lineage.kuzu
    volumes:
      - lineage-data:/data
    healthcheck:
      test: ["CMD", "nova", "doctor", "--check-storage"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  lineage-data:
    driver: local
"""
