# Copyright 2024 NovaFabric Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""W3C PROV-DM mapping table for cap-002 edge types (FR-08, ADR-0044).

Mapping table (FR-08):
  spawned       → prov:wasGeneratedBy      (child was generated by parent execution)
  contains      → prov:wasInformedBy       (structural containment / data flow)
  delegated_to  → prov:actedOnBehalfOf     (agent delegation)
  replayed_from → novafabric:replayedFrom  (NovaFabric-specific; no direct PROV-DM)

NOTE: A full PROV-N exporter is deferred to a future version per build-prompt scope.
This module provides the mapping table and a JSON-LD context stub for round-trip tests.
"""

from __future__ import annotations

from typing import Any

from novafabric.capsule.schema import EdgeType

# ── PROV-DM mapping ────────────────────────────────────────────────────────

PROV_DM_MAPPING: dict[EdgeType, dict[str, str]] = {
    EdgeType.spawned: {
        "prov_term": "wasGeneratedBy",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#wasGeneratedBy",
        "description": (
            "The target entity was generated by the source activity. "
            "Used when a child capsule is spawned by a parent execution."
        ),
        "adr": "ADR-0044",
    },
    EdgeType.contains: {
        "prov_term": "wasInformedBy",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#wasInformedBy",
        "description": (
            "The target activity was informed by the source activity. "
            "Used for structural containment (parent contains worker capsules) "
            "and general data-flow edges."
        ),
        "adr": "ADR-0044",
    },
    EdgeType.delegated_to: {
        "prov_term": "actedOnBehalfOf",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#actedOnBehalfOf",
        "description": (
            "The source agent acted on behalf of (delegated to) the target agent. "
            "Used when a driver process delegates sub-tasks to worker agents."
        ),
        "adr": "ADR-0044",
    },
    EdgeType.replayed_from: {
        "prov_term": "replayedFrom",
        "prov_namespace": "https://novafabric.io/prov#",
        "prov_iri": "https://novafabric.io/prov#replayedFrom",
        "description": (
            "NovaFabric-specific edge: the target run was replayed from the source run. "
            "No direct W3C PROV-DM counterpart; this edge carries replay provenance."
        ),
        "adr": "ADR-0044",
    },
    EdgeType.member_of_session: {
        # prov:hadMember is PROV-DM's collection-membership term — precisely
        # what a grouping edge is. Mapping it to a causal term (wasInformedBy,
        # wasGeneratedBy) would assert a causal relationship between session
        # members that ADR-0122 explicitly denies: members are independent
        # runs performed in sequence, not one causing the next.
        "prov_term": "hadMember",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#hadMember",
        "description": (
            "The source session (a prov:Collection) had the target run as a member. "
            "A grouping edge, not a causal one: session members are independent "
            "runs performed in sequence (ADR-0122 D3)."
        ),
        "adr": "ADR-0122",
    },
    EdgeType.wrote_memory: {
        "prov_term": "wasGeneratedBy",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#wasGeneratedBy",
        "description": (
            "The memory item was generated by the source run. Emitted on a "
            "memory write (ADR-0143 P1)."
        ),
        "adr": "ADR-0143",
    },
    EdgeType.read_memory: {
        # prov:used is PROV-DM's consumption term — an activity used an entity.
        # Mapping a read to wasGeneratedBy would claim the run PRODUCED the
        # item it merely consumed, inverting the causality a back-trace walks.
        "prov_term": "used",
        "prov_namespace": "http://www.w3.org/ns/prov#",
        "prov_iri": "http://www.w3.org/ns/prov#used",
        "description": (
            "The target run used (read) the source memory item. Emitted on a "
            "memory read (ADR-0143 P1)."
        ),
        "adr": "ADR-0143",
    },
}


# ── JSON-LD context stub ───────────────────────────────────────────────────


def get_jsonld_context() -> dict[str, Any]:
    """Return a JSON-LD context stub mapping cap-002 edge types to PROV IRIs.

    This is a stub for round-trip testing (FR-08 acceptance). A full
    PROV-N exporter is out of scope for Phase 3.
    """
    context: dict[str, Any] = {
        "@context": {
            "prov": "http://www.w3.org/ns/prov#",
            "novafabric": "https://novafabric.io/prov#",
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            # cap-002 edge type → IRI mappings
            "spawned": {"@id": "prov:wasGeneratedBy"},
            "contains": {"@id": "prov:wasInformedBy"},
            "delegated_to": {"@id": "prov:actedOnBehalfOf"},
            "replayed_from": {"@id": "novafabric:replayedFrom"},
            "member_of_session": {"@id": "prov:hadMember"},
            "wrote_memory": {"@id": "prov:wasGeneratedBy"},
            "read_memory": {"@id": "prov:used"},
            # Run capsule node type
            "RunCapsule": "novafabric:RunCapsule",
            "global_run_id": {"@id": "novafabric:globalRunId", "@type": "xsd:string"},
            "run_id": {"@id": "novafabric:runId", "@type": "xsd:string"},
            "edge_type": {"@id": "novafabric:edgeType"},
            "source_run_id": {"@id": "novafabric:sourceRunId"},
            "target_run_id": {"@id": "novafabric:targetRunId"},
        }
    }
    return context


def edge_to_jsonld(
    edge_type: EdgeType,
    source_run_id: str,
    target_run_id: str,
    edge_id: str,
    attributes: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Serialise a single edge as a JSON-LD node with PROV-DM mapping.

    This is a stub implementation for round-trip testing (FR-08).
    """
    mapping = PROV_DM_MAPPING[edge_type]
    node: dict[str, Any] = {
        "@context": get_jsonld_context()["@context"],
        "@id": f"novafabric:edge/{edge_id}",
        "@type": "novafabric:LineageEdge",
        "novafabric:edgeType": edge_type.value,
        "novafabric:provDmTerm": mapping["prov_iri"],
        "novafabric:sourceRunId": source_run_id,
        "novafabric:targetRunId": target_run_id,
    }
    if attributes:
        node["novafabric:attributes"] = attributes
    return node


def get_mapping_for_edge(edge_type: EdgeType) -> dict[str, str]:
    """Return the PROV-DM mapping entry for a given edge type."""
    return PROV_DM_MAPPING[edge_type]
