"""Single-file offline HTML renderer for a ``TrendReport`` (ADR-0131 P3).

Emits exactly **one** self-contained ``.html`` file satisfying the normative
static-HTML contract of ``design/spec/trend-report-v0.md``:

- zero external requests — no CDN, fonts, images, scripts, ``fetch``/sockets;
- all CSS inline in ``<style>``; **no JavaScript at all** — the chart is a
  pre-rendered inline ``<svg>`` generated with the Python standard library
  only (line/area for ``day``/``week``, bars for ``asset``), mirroring the
  ADR-0038 "inline SVG, no charting library" precedent;
- gap points (``value: null``) render as a visible break, never as zero;
- the exact ``TrendReport`` JSON is embedded inline in
  ``<script type="application/json" id="trend-report-data">``;
- renders fully from ``file://`` with no server and no build toolchain.

The file is an artifact, never a served page. Uses Jinja2 (existing Tier-A
runtime dependency; ADR-0024). Status: **experimental**.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

from jinja2 import Environment
from markupsafe import Markup

_WIDTH = 720
_HEIGHT = 260
_ML, _MR, _MT, _MB = 64, 16, 16, 44  # margins: left, right, top, bottom
_MAX_X_LABELS = 10
_MAX_LABEL_CHARS = 18

_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ page_title }}</title>
<style>
:root { color-scheme: light dark; }
body { font-family: system-ui, sans-serif; margin: 2rem auto; max-width: 60rem;
       padding: 0 1rem; line-height: 1.5; }
h1 { font-size: 1.4rem; border-bottom: 2px solid currentColor; padding-bottom: .4rem; }
h2 { font-size: 1.1rem; margin-top: 2rem; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { border: 1px solid rgba(128,128,128,.5); padding: .35rem .6rem; text-align: left; }
th { background: rgba(128,128,128,.15); }
code { font-family: ui-monospace, monospace; font-size: .85em; }
.none { opacity: .65; font-style: italic; }
.notice { border: 1px solid rgba(128,128,128,.5); background: rgba(128,128,128,.1);
          padding: .6rem .8rem; margin: 1rem 0; font-size: .9rem; }
svg { max-width: 100%; height: auto; }
.mark { fill: rgba(30,110,190,.85); }
.stroke { stroke: rgba(30,110,190,.85); stroke-width: 2; fill: none; }
.axis { stroke: rgba(128,128,128,.7); stroke-width: 1; }
.tick { font-size: 10px; fill: currentColor; }
footer { margin-top: 2.5rem; font-size: .8rem; opacity: .75; }
</style>
</head>
<body>
<h1>{{ page_title }}</h1>
<p class="notice">Offline snapshot generated by <code>nova trend</code>
(ADR-0131) — a read-only trend report over local capsules. It is a snapshot
artifact, <strong>not</strong> a live monitor: no thresholds, no polling, no
notifications.</p>

<h2>Report</h2>
<table>
<tr><th>Metric</th><td><code>{{ report.metric }}</code></td></tr>
<tr><th>Group by</th><td>{{ report.group_by }}</td></tr>
{% if report.stat is defined %}<tr><th>Statistic</th><td>{{ report.stat }}</td></tr>
{% endif %}<tr><th>Window</th>
<td>{{ report.window.since }} &#8594; {{ report.window.until }}</td></tr>
<tr><th>Capsules</th><td>{{ report.capsule_count }} contributing,
{{ report.skipped_count }} skipped</td></tr>
{% if report.view is defined %}<tr><th>Saved view</th>
<td><code>{{ report.view }}</code></td></tr>
{% endif %}</table>

<h2>Chart</h2>
{% if chart_svg %}{{ chart_svg }}{% else %}<p class="none">no data in window
&#8212; every bucket is a gap or the series is empty</p>{% endif %}

<h2>Series ({{ report.series | length }} bucket{{ "s" if report.series | length != 1 }})</h2>
{% if report.series %}<table>
<tr><th>Bucket</th><th>Value</th><th>n</th></tr>
{% for p in report.series %}<tr>
<td><code>{{ p.bucket }}</code></td>
<td>{% if p.value is not none %}{{ "%.6g" | format(p.value) }}{% else %}<span
class="none">gap</span>{% endif %}</td>
<td>{{ p.n }}</td>
</tr>
{% endfor %}</table>{% else %}<p class="none">no buckets (no capsules matched
the window)</p>{% endif %}

{% if report.warnings is defined and report.warnings %}<h2>Warnings</h2>
<ul>{% for w in report.warnings %}<li>{{ w }}</li>{% endfor %}</ul>
{% endif %}

<footer>
Generated by {{ report.generator }} at {{ report.generated_at }} &#183;
TrendReport schema {{ report.schema_version }} &#183; self-contained offline
page (ADR-0131) &#8212; the embedded canonical JSON is in the
<code>trend-report-data</code> block below (View Source).
</footer>

<script type="application/json" id="trend-report-data">
{{ report_json }}
</script>
</body>
</html>
"""


def _fmt(value: float) -> str:
    return f"{value:.6g}"


def _scale(values: list[float]) -> tuple[float, float]:
    """Y-axis domain: zero-based unless the data dips below zero."""
    low = min(0.0, min(values))
    high = max(values)
    if high == low:
        high = low + 1.0
    return low, high


def _svg_time_chart(series: list[dict[str, Any]]) -> str | None:
    """Pre-rendered line chart; gap points break the line (never zero)."""
    values = [p["value"] for p in series if p["value"] is not None]
    if not values:
        return None
    low, high = _scale([float(v) for v in values])
    plot_w = _WIDTH - _ML - _MR
    plot_h = _HEIGHT - _MT - _MB
    n = len(series)

    def x_of(i: int) -> float:
        return _ML + (i + 0.5) * plot_w / n

    def y_of(v: float) -> float:
        return _MT + plot_h * (1.0 - (v - low) / (high - low))

    parts: list[str] = [_axes(low, high)]
    # Contiguous non-null runs become one <path> each; a gap is a visible break.
    segment: list[tuple[float, float]] = []

    def flush() -> None:
        if len(segment) >= 2:
            d = "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in segment)
            parts.append(f'<path class="stroke" d="{d}"/>')
        segment.clear()

    for i, point in enumerate(series):
        if point["value"] is None:
            flush()
            continue
        xy = (x_of(i), y_of(float(point["value"])))
        segment.append(xy)
        parts.append(f'<circle class="mark" cx="{xy[0]:.1f}" cy="{xy[1]:.1f}" r="3"/>')
    flush()
    parts.append(_x_labels(series, x_of))
    return _svg(parts)


def _svg_bar_chart(series: list[dict[str, Any]]) -> str | None:
    """Pre-rendered bar chart for the categorical ``asset`` grouping."""
    values = [float(p["value"]) for p in series if p["value"] is not None]
    if not values:
        return None
    low, high = _scale(values)
    plot_w = _WIDTH - _ML - _MR
    plot_h = _HEIGHT - _MT - _MB
    n = len(series)
    slot = plot_w / n
    bar_w = slot * 0.6

    def x_of(i: int) -> float:
        return _ML + (i + 0.5) * slot

    def y_of(v: float) -> float:
        return _MT + plot_h * (1.0 - (v - low) / (high - low))

    parts: list[str] = [_axes(low, high)]
    zero_y = y_of(max(low, 0.0))
    for i, point in enumerate(series):
        if point["value"] is None:
            continue
        top = y_of(float(point["value"]))
        y0, y1 = min(top, zero_y), max(top, zero_y)
        parts.append(
            f'<rect class="mark" x="{x_of(i) - bar_w / 2:.1f}" y="{y0:.1f}" '
            f'width="{bar_w:.1f}" height="{max(y1 - y0, 1.0):.1f}"/>'
        )
    parts.append(_x_labels(series, x_of))
    return _svg(parts)


def _axes(low: float, high: float) -> str:
    plot_bottom = _HEIGHT - _MB
    return (
        f'<line class="axis" x1="{_ML}" y1="{_MT}" x2="{_ML}" y2="{plot_bottom}"/>'
        f'<line class="axis" x1="{_ML}" y1="{plot_bottom}" '
        f'x2="{_WIDTH - _MR}" y2="{plot_bottom}"/>'
        f'<text class="tick" x="{_ML - 6}" y="{_MT + 4}" '
        f'text-anchor="end">{escape(_fmt(high))}</text>'
        f'<text class="tick" x="{_ML - 6}" y="{plot_bottom + 4}" '
        f'text-anchor="end">{escape(_fmt(low))}</text>'
    )


def _x_labels(series: list[dict[str, Any]], x_of: Any) -> str:
    step = max(1, -(-len(series) // _MAX_X_LABELS))  # ceil division
    labels: list[str] = []
    for i in range(0, len(series), step):
        raw = str(series[i]["bucket"])
        if len(raw) > _MAX_LABEL_CHARS:
            raw = raw[: _MAX_LABEL_CHARS - 1] + "…"
        labels.append(
            f'<text class="tick" x="{x_of(i):.1f}" y="{_HEIGHT - _MB + 16}" '
            f'text-anchor="middle">{escape(raw)}</text>'
        )
    return "".join(labels)


def _svg(parts: list[str]) -> str:
    body = "".join(parts)
    return (
        f'<svg viewBox="0 0 {_WIDTH} {_HEIGHT}" width="{_WIDTH}" '
        f'height="{_HEIGHT}" role="img" '
        f'aria-label="trend chart">{body}</svg>'
    )


def render_trend_html(report: dict[str, Any]) -> str:
    """Render a ``TrendReport`` dict as the self-contained HTML page."""
    env = Environment(autoescape=True)
    template = env.from_string(_TEMPLATE)
    page_title = f"Trend — {report['metric']} by {report['group_by']}"
    if report["group_by"] == "asset":
        chart = _svg_bar_chart(report["series"])
    else:
        chart = _svg_time_chart(report["series"])
    # JSON-escape every "<" (unicode escape u003c) so the embedded payload can
    # never close the <script> block early; it stays valid JSON.
    report_json = json.dumps(report, indent=2, ensure_ascii=False).replace("<", "\\u003c")
    return template.render(
        report=report,
        page_title=page_title,
        chart_svg=Markup(chart) if chart else None,
        report_json=Markup(report_json),
    )


def write_trend_html(report: dict[str, Any], output: str | Path) -> Path:
    """Write the single self-contained HTML artifact; returns the path."""
    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_trend_html(report), encoding="utf-8")
    return out_path
