apiVersion: v1
kind: Service
metadata:
  name: {{ include "janusgraph.fullname" . }}
  labels:
    {{- include "janusgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "janusgraph.selectorLabels" . | nindent 4 }}
  ports:
    - name: gremlin
      port: {{ .Values.service.port }}
      targetPort: gremlin
      protocol: TCP
