"""E-7 tests: deployment profile generators (KuzuDB vertical + JanusGraph minimal)."""

from __future__ import annotations

import yaml

from novafabric.lineage.profiles.janusgraph_minimal import generate_janusgraph_minimal_profile
from novafabric.lineage.profiles.kuzudb_vertical import generate_kuzudb_vertical_profile


class TestKuzudbVerticalProfile:
    def test_is_valid_yaml(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        result = yaml.safe_load(profile)
        assert result is not None

    def test_has_services_key(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        assert "services" in data

    def test_has_volumes_key(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        assert "volumes" in data

    def test_nova_lineage_service_present(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        assert "nova-lineage" in data["services"]

    def test_kuzudb_backend_env_var(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        env = data["services"]["nova-lineage"]["environment"]
        assert env.get("NOVA_LINEAGE_BACKEND") == "kuzudb"

    def test_kuzu_db_path_env_var(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        env = data["services"]["nova-lineage"]["environment"]
        assert "/data/lineage.kuzu" in env.get("NOVA_KUZU_DB_PATH", "")

    def test_data_volume_mounted(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        service = data["services"]["nova-lineage"]
        volumes = service.get("volumes", [])
        assert any("/data" in str(v) for v in volumes)

    def test_healthcheck_present(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        data = yaml.safe_load(profile)
        assert "healthcheck" in data["services"]["nova-lineage"]

    def test_gate_condition_comment_present(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        assert "Gate condition" in profile

    def test_generated_by_comment_present(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        assert "Generated by nova lineage-store profile" in profile

    def test_node_size_reflected_in_output(self) -> None:
        profile = generate_kuzudb_vertical_profile(node_size="32g-ram-1t-nvme")
        assert "32g-ram-1t-nvme" in profile

    def test_image_tag_in_service(self) -> None:
        profile = generate_kuzudb_vertical_profile(image_tag="v0.9.0")
        data = yaml.safe_load(profile)
        image = data["services"]["nova-lineage"]["image"]
        assert "v0.9.0" in image

    def test_returns_string(self) -> None:
        assert isinstance(generate_kuzudb_vertical_profile(), str)

    def test_default_image_tag_latest(self) -> None:
        profile = generate_kuzudb_vertical_profile()
        assert "latest" in profile


class TestJanusGraphMinimalProfile:
    def test_is_valid_yaml(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        result = yaml.safe_load(profile)
        assert result is not None

    def test_has_services_key(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "services" in data

    def test_has_volumes_key(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "volumes" in data

    def test_has_cassandra_service(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        assert "cassandra" in profile.lower()

    def test_has_janusgraph_service(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "janusgraph" in data["services"]

    def test_replication_factor_default_3(self) -> None:
        profile = generate_janusgraph_minimal_profile(replication_factor=3)
        assert "3" in profile

    def test_replication_factor_1_valid_yaml(self) -> None:
        profile = generate_janusgraph_minimal_profile(replication_factor=1)
        result = yaml.safe_load(profile)
        assert result is not None

    def test_replication_factor_3_valid_yaml(self) -> None:
        profile = generate_janusgraph_minimal_profile(replication_factor=3)
        result = yaml.safe_load(profile)
        assert result is not None

    def test_janusgraph_depends_on_cassandra(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        jg = data["services"]["janusgraph"]
        depends = jg.get("depends_on", {})
        assert "cassandra" in depends

    def test_cassandra_healthcheck_present(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "healthcheck" in data["services"]["cassandra"]

    def test_janusgraph_healthcheck_present(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "healthcheck" in data["services"]["janusgraph"]

    def test_returns_string(self) -> None:
        assert isinstance(generate_janusgraph_minimal_profile(), str)

    def test_custom_image_tag(self) -> None:
        profile = generate_janusgraph_minimal_profile(image_tag="1.0.0")
        assert "1.0.0" in profile

    def test_cassandra_volume_defined(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "cassandra-data" in data["volumes"]

    def test_janusgraph_volume_defined(self) -> None:
        profile = generate_janusgraph_minimal_profile()
        data = yaml.safe_load(profile)
        assert "janusgraph-data" in data["volumes"]
