# Copyright 2024 NovaFabric Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Agentic-commerce settlement evidence (ADR-0163, experimental).

Record-only: NovaFabric records the provenance of money another system
moved. It never processes payments, holds or moves funds, provisions tokens,
or adjudicates a dispute.
"""

from novafabric.settlement._refs import InvalidIdentityRefError
from novafabric.settlement.agreement import (
    AGREEMENT_FIELD,
    AgreementRecord,
    AgreementVerification,
    MalformedAgreementError,
    NonCanonicalTermsError,
    agreement_from_facet,
    attach_agreement,
    build_agreement,
    digest_terms,
    verify_agreement,
)
from novafabric.settlement.chain import (
    CHAIN_FIELD,
    MAX_CHAIN_HOPS,
    A2AChainFinding,
    A2AChainVerification,
    A2APaymentHop,
    BrokenA2AChainError,
    MalformedA2AChainError,
    attach_chain,
    build_a2a_chain,
    chain_from_facet,
    verify_a2a_chain,
    walk_back,
)
from novafabric.settlement.facet import (
    FACET_NAME,
    SCHEMA_VERSION,
    UNKNOWN_FINALITY,
    AuthorizedTerms,
    Discrepancy,
    DiscrepancyLaunderedError,
    FinalityRecord,
    FinalitySource,
    FinalityState,
    InvalidReferenceError,
    MandateReconciliation,
    Money,
    NonRepudiationBinding,
    ObservedSettlement,
    PaymentSecretRejectedError,
    Protocol,
    SettlementFacet,
    SigScheme,
    UnconfirmedFinalityError,
    attach_facet,
    build_facet,
    build_non_repudiation,
    digest_artifact,
    finality_state,
    is_final,
    reconcile,
    reject_payment_secrets,
    verify_non_repudiation,
    verify_ref_binding,
)
from novafabric.settlement.invoice import (
    INVOICE_FIELD,
    DocumentType,
    InvoiceMatchLaunderedError,
    InvoiceMismatch,
    InvoiceReceipt,
    InvoiceVerification,
    MalformedInvoiceError,
    attach_invoice,
    bind_invoice,
    compare_to_settlement,
    invoice_from_facet,
    verify_invoice,
)

__all__ = [
    "A2AChainFinding",
    "A2AChainVerification",
    "A2APaymentHop",
    "AGREEMENT_FIELD",
    "AgreementRecord",
    "AgreementVerification",
    "AuthorizedTerms",
    "BrokenA2AChainError",
    "CHAIN_FIELD",
    "Discrepancy",
    "DiscrepancyLaunderedError",
    "DocumentType",
    "FACET_NAME",
    "FinalityRecord",
    "FinalitySource",
    "FinalityState",
    "INVOICE_FIELD",
    "InvalidIdentityRefError",
    "InvalidReferenceError",
    "InvoiceMatchLaunderedError",
    "InvoiceMismatch",
    "InvoiceReceipt",
    "InvoiceVerification",
    "MAX_CHAIN_HOPS",
    "MalformedA2AChainError",
    "MalformedAgreementError",
    "MalformedInvoiceError",
    "MandateReconciliation",
    "Money",
    "NonCanonicalTermsError",
    "NonRepudiationBinding",
    "ObservedSettlement",
    "PaymentSecretRejectedError",
    "Protocol",
    "SCHEMA_VERSION",
    "SettlementFacet",
    "SigScheme",
    "UNKNOWN_FINALITY",
    "UnconfirmedFinalityError",
    "agreement_from_facet",
    "attach_agreement",
    "attach_chain",
    "attach_facet",
    "attach_invoice",
    "bind_invoice",
    "build_a2a_chain",
    "build_agreement",
    "build_facet",
    "build_non_repudiation",
    "chain_from_facet",
    "compare_to_settlement",
    "digest_artifact",
    "digest_terms",
    "finality_state",
    "invoice_from_facet",
    "is_final",
    "reconcile",
    "reject_payment_secrets",
    "verify_a2a_chain",
    "verify_agreement",
    "verify_invoice",
    "verify_non_repudiation",
    "verify_ref_binding",
    "walk_back",
]
