#!/usr/bin/env python3
"""Regenerate ``api/openapi-dashboard.yaml`` from the live serve app (ADR-0240).

The dashboard API contract is generated, never hand-written — the BL-041
lesson. It is dumped from the FastAPI app built by
``novafabric.serve.app.create_app``, then post-processed:

- operations without an ``operationId`` get ``x-nova-contract: pending`` —
  the document is honest at every intermediate state of the annotation ratchet
  (``tests/serve/test_openapi_dashboard_contract.py``);
- WebSocket routes (which OpenAPI 3.1 cannot express) are inventoried under
  ``x-nova-websockets`` rather than pretended into paths.

Usage:
    uv run python scripts/gen_openapi_dashboard.py           # rewrite
    uv run python scripts/gen_openapi_dashboard.py --check   # exit 1 if stale
"""

from __future__ import annotations

import sys
import tempfile
from importlib.metadata import version as pkg_version
from pathlib import Path
from typing import Any

import yaml
from starlette.routing import WebSocketRoute

from novafabric.serve.app import create_app

_OUT = Path(__file__).resolve().parent.parent / "api" / "openapi-dashboard.yaml"

_INFO_DESCRIPTION = (
    "The NovaFabric dashboard (serve) API — the FROZEN local-dashboard surface\n"
    "(ADR-0183): serve/ migrates incrementally into the strategic /v0 server API;\n"
    "new integrations should prefer /v0 (api/openapi.yaml). This document exists\n"
    "so that surface is inventoried, authorizable (ADR-0228/0229), and migratable\n"
    "route-by-route — it is not an endorsement of new serve/ endpoints.\n"
    "Authentication: the shared dashboard token (Bearer header preferred; ?token=\n"
    "query accepted for SSE), loopback bind by default (ADR-0184).\n"
    "Operations marked x-nova-contract: pending are not yet annotated with an\n"
    "operationId + declared response schema; the set may only shrink (ADR-0240 D4).\n\n"
    "This file is GENERATED by scripts/gen_openapi_dashboard.py — do not edit it\n"
    "by hand. Regenerate after changing any serve route."
)


def build_app() -> Any:
    """The serve app exactly as the contract sees it (no static, no topology)."""
    tmp = Path(tempfile.mkdtemp(prefix="nova-openapi-dashboard-"))
    capsule_dir = tmp / "runs"
    capsule_dir.mkdir()
    return create_app(
        token="contract-generation-token",
        capsule_dir=capsule_dir,
        db_path=tmp / "registry.db",
        static_dir=None,
    )


def render() -> str:
    app = build_app()
    spec = app.openapi()

    spec["info"] = {
        "title": "NovaFabric Dashboard API (serve)",
        "version": pkg_version("novafabric"),
        "description": _INFO_DESCRIPTION,
        "license": {"name": "Apache-2.0"},
    }

    pending = 0
    for path_item in spec.get("paths", {}).values():
        for method, op in path_item.items():
            if method not in {"get", "post", "put", "delete", "patch"}:
                continue
            if not isinstance(op, dict):
                continue
            gen_id = op.get("operationId", "")
            # FastAPI auto-generates snake_case ids from function names when no
            # explicit operation_id is set; explicit ADR-0240 ids are camelCase
            # with the "dashboard" prefix. Anything else is unannotated.
            if not gen_id.startswith("dashboard"):
                op.pop("operationId", None)
                op["x-nova-contract"] = "pending"
                pending += 1

    spec["x-nova-websockets"] = sorted(
        route.path
        for route in app.routes
        if isinstance(route, WebSocketRoute)
    )
    spec["x-nova-contract-pending-count"] = pending

    return yaml.safe_dump(spec, sort_keys=True, allow_unicode=True, width=100)


def main() -> int:
    content = render()
    if "--check" in sys.argv[1:]:
        if not _OUT.exists() or _OUT.read_text() != content:
            print(f"{_OUT} is stale — run: uv run python scripts/gen_openapi_dashboard.py")
            return 1
        print(f"{_OUT} is current")
        return 0
    _OUT.write_text(content)
    print(f"wrote {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
