# Copyright 2024 NovaFabric Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Examiner-mode evidence packet exporters.

Three exporters for regulated-industry and audit contexts:

  BagItExporter   — RFC 8493 BagIt packaging for digital preservation.
  PCCPExporter    — FDA Predetermined Change Control Plan (21 CFR 880).
  ISO42001Exporter — ISO/IEC 42001:2023 AI Management System evidence package.

These exporters are self-contained and do not require server mode or a live
database connection.  They operate on the local capsule data directory.
"""

from __future__ import annotations

import json
import stat
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

from novafabric._hashutil import sha256_file_hex, sha256_hex

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _sha256_file(path: Path) -> str:
    """Return the lowercase hex SHA-256 of a file (streamed, memory-bounded)."""
    return sha256_file_hex(path)


def _sha256_bytes(data: bytes) -> str:
    """Return the lowercase hex SHA-256 of *data*."""
    return sha256_hex(data)


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _now_iso_full() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f") + "Z"


def _load_manifest(capsule_dir: Path) -> dict[str, Any]:
    """Load capsule.yaml from *capsule_dir* (or return empty dict if absent)."""
    path = capsule_dir / "capsule.yaml"
    if not path.exists():
        return {}
    data = yaml.safe_load(path.read_text())
    return data if isinstance(data, dict) else {}


# ---------------------------------------------------------------------------
# BagItExporter — RFC 8493
# ---------------------------------------------------------------------------

_BAGIT_TXT = "BagIt-Version: 1.0\nTag-File-Character-Encoding: UTF-8\n"

_VERIFY_SH = """\
#!/bin/bash
# Offline BagIt verification script — generated by NovaFabric
# Usage: ./verify.sh
set -e
echo "Verifying BagIt manifest..."
while IFS='  ' read -r checksum filepath; do
    actual=$(sha256sum "data/$filepath" | awk '{print $1}')
    if [ "$actual" != "$checksum" ]; then
        echo "FAIL: $filepath"
        exit 1
    fi
done < manifest-sha256.txt
echo "All checksums verified OK"
"""


class BagItExporter:
    """RFC 8493 BagIt packaging exporter.

    Produces a self-contained BagIt ZIP that can be transferred to a digital
    preservation repository (e.g., DSpace, Archivematica) without any
    NovaFabric-specific tooling.

    The bag contains:

    - ``bagit.txt``            — BagIt version and encoding declaration
    - ``bag-info.txt``         — bag metadata (size, date, external identifier)
    - ``manifest-sha256.txt``  — SHA-256 checksums of all ``data/`` files
    - ``tagmanifest-sha256.txt`` — SHA-256 checksums of all tag files
    - ``data/``                — evidence payload (capsule files)
    - ``verify.sh``            — standalone bash script for offline verification

    Usage::

        exporter = BagItExporter(capsule_id="run-abc123", data_dir=Path("capsules/run-abc123"))
        bag_path = exporter.export(output_dir=Path("/tmp/bags"))
    """

    def __init__(self, capsule_id: str, data_dir: Path) -> None:
        self.capsule_id = capsule_id
        self.data_dir = data_dir

    def export(
        self,
        output_dir: Path,
        include_audit_report: bool = True,
        contact_email: str = "",
    ) -> Path:
        """Create a BagIt-format ZIP at ``output_dir/{capsule_id}-bag.zip``.

        Args:
            output_dir:          Directory in which to write the ZIP.
            include_audit_report: If True and ``audit-report.json`` exists in
                                  data_dir, include it in the bag payload.
            contact_email:       Optional contact email written to bag-info.txt.

        Returns:
            Path to the written ZIP file.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{self.capsule_id}-bag.zip"

        # Collect payload files from the capsule directory
        payload: dict[str, bytes] = {}  # filename (relative to data/) -> bytes

        # Always include capsule manifest if present
        for candidate in ["capsule.yaml", "capsule-manifest.json"]:
            src = self.data_dir / candidate
            if src.exists():
                payload[candidate] = src.read_bytes()

        # Include evidence bundle zip if present
        for zip_path in sorted(self.data_dir.glob("*.zip")):
            if zip_path != output_path:
                payload[zip_path.name] = zip_path.read_bytes()

        # Include audit report
        if include_audit_report:
            audit_path = self.data_dir / "audit-report.json"
            if audit_path.exists():
                payload["audit-report.json"] = audit_path.read_bytes()

        # Compute checksums
        manifest_lines: list[str] = []
        for filename, data in sorted(payload.items()):
            digest = _sha256_bytes(data)
            manifest_lines.append(f"{digest}  {filename}")
        manifest_sha256_content = "\n".join(manifest_lines) + "\n" if manifest_lines else ""

        # Compute total payload size
        total_bytes = sum(len(d) for d in payload.values())

        # Build bag-info.txt
        bag_info_lines = [
            "Bag-Software-Agent: novafabric",
            f"Bag-Size: {total_bytes}",
            f"Bagging-Date: {_now_iso()}",
            f"External-Identifier: {self.capsule_id}",
            "Source-Organization: NovaFabric",
        ]
        if contact_email:
            bag_info_lines.append(f"Contact-Email: {contact_email}")
        bag_info_content = "\n".join(bag_info_lines) + "\n"

        # Tag manifests (checksums of the tag files themselves)
        tag_files = {
            "bagit.txt": _BAGIT_TXT.encode(),
            "bag-info.txt": bag_info_content.encode(),
            "manifest-sha256.txt": manifest_sha256_content.encode(),
        }
        tag_manifest_lines: list[str] = []
        for tagname, tagdata in sorted(tag_files.items()):
            digest = _sha256_bytes(tagdata)
            tag_manifest_lines.append(f"{digest}  {tagname}")
        tag_manifest_sha256_content = "\n".join(tag_manifest_lines) + "\n"

        # Write ZIP
        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
            prefix = self.capsule_id

            # Tag files
            zf.writestr(f"{prefix}/bagit.txt", _BAGIT_TXT)
            zf.writestr(f"{prefix}/bag-info.txt", bag_info_content)
            zf.writestr(f"{prefix}/manifest-sha256.txt", manifest_sha256_content)
            zf.writestr(f"{prefix}/tagmanifest-sha256.txt", tag_manifest_sha256_content)

            # verify.sh — make executable in the ZIP info
            verify_info = zipfile.ZipInfo(f"{prefix}/verify.sh")
            verify_info.compress_type = zipfile.ZIP_DEFLATED
            verify_info.external_attr = (
                stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
            ) << 16
            zf.writestr(verify_info, _VERIFY_SH)

            # Payload data/ directory
            for filename, data in sorted(payload.items()):
                zf.writestr(f"{prefix}/data/{filename}", data)

        return output_path


# ---------------------------------------------------------------------------
# PCCPExporter — FDA Predetermined Change Control Plan
# ---------------------------------------------------------------------------


class PCCPExporter:
    """FDA Predetermined Change Control Plan (PCCP) exporter.

    A PCCP documents planned AI modifications under 21 CFR 880.  This exporter
    compares a ``baseline_capsule`` to a ``proposed_capsule`` and produces a
    three-section JSON document per FDA guidance on PCCP for AI/ML-based
    Software as a Medical Device (SaMD).

    Sections:
      1. Description of Modifications
      2. Modification Protocol (testing approach and acceptance criteria)
      3. Impact Assessment (safety, benefit-risk, risk controls)

    Usage::

        exporter = PCCPExporter(
            baseline_capsule_id="run-v1",
            proposed_capsule_id="run-v2",
            data_dir=Path("capsules"),
        )
        out = exporter.export(output_path=Path("/tmp/pccp.json"))
    """

    def __init__(
        self,
        baseline_capsule_id: str,
        proposed_capsule_id: str,
        data_dir: Path,
    ) -> None:
        self.baseline_capsule_id = baseline_capsule_id
        self.proposed_capsule_id = proposed_capsule_id
        self.data_dir = data_dir

    def export(self, output_path: Path) -> Path:
        """Export the PCCP document as JSON.

        Args:
            output_path: File path to write the PCCP JSON.

        Returns:
            Path to the written file.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        pccp: dict[str, Any] = {
            "@context": "https://novafabric.dev/schemas/pccp/v1",
            "pccp_version": "1.0",
            "generated_at": _now_iso_full(),
            "section_1_description_of_modifications": {
                "baseline_capsule": self.baseline_capsule_id,
                "proposed_capsule": self.proposed_capsule_id,
                "modification_summary": self._compute_modification_summary(),
            },
            "section_2_modification_protocol": {
                "testing_approach": "Automated replay comparison via nova diff",
                "performance_metrics": self._extract_performance_metrics(),
                "acceptance_criteria": "No regression in eval suite scores",
            },
            "section_3_impact_assessment": {
                "safety_impact": "See attached diff report",
                "benefit_risk_analysis": self._extract_benefit_risk(),
                "risk_controls": [
                    "NovaSeal signing",
                    "Rego policy gates",
                    "Maker-checker approval",
                ],
            },
        }

        output_path.write_text(json.dumps(pccp, indent=2), encoding="utf-8")
        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _load_capsule_manifest(self, capsule_id: str) -> dict[str, Any]:
        capsule_dir = self.data_dir / capsule_id
        if not capsule_dir.exists():
            # Try treating data_dir as the capsule dir directly for the given ID
            manifest_path = self.data_dir / "capsule.yaml"
            if manifest_path.exists():
                data = yaml.safe_load(manifest_path.read_text())
                return data if isinstance(data, dict) else {}
            return {}
        return _load_manifest(capsule_dir)

    def _compute_modification_summary(self) -> str:
        baseline = self._load_capsule_manifest(self.baseline_capsule_id)
        proposed = self._load_capsule_manifest(self.proposed_capsule_id)

        baseline_model = baseline.get("model_id") or baseline.get("asset_name", "unknown")
        proposed_model = proposed.get("model_id") or proposed.get("asset_name", "unknown")

        if baseline_model == proposed_model:
            return (
                f"Model configuration update: {baseline_model}. "
                "See section 2 for testing protocol and acceptance criteria."
            )
        return (
            f"Model change from {baseline_model!r} to {proposed_model!r}. "
            "See section 2 for testing protocol and acceptance criteria."
        )

    def _extract_performance_metrics(self) -> list[dict[str, Any]]:
        proposed = self._load_capsule_manifest(self.proposed_capsule_id)
        metrics: list[dict[str, Any]] = []

        eval_results = proposed.get("eval_results") or proposed.get("evals", [])
        if isinstance(eval_results, list):
            for ev in eval_results:
                if isinstance(ev, dict):
                    metrics.append({
                        "suite": ev.get("suite_name", "unknown"),
                        "score": ev.get("score"),
                        "threshold": ev.get("threshold"),
                    })

        if not metrics:
            metrics = [
                {
                    "suite": "nova-smoke-v1",
                    "score": None,
                    "threshold": None,
                    "note": "No eval results found in proposed capsule",
                }
            ]
        return metrics

    def _extract_benefit_risk(self) -> str:
        proposed = self._load_capsule_manifest(self.proposed_capsule_id)
        notes = proposed.get("benefit_risk_notes") or proposed.get("release_notes", "")
        if notes:
            return str(notes)
        return (
            "Operator must supply benefit-risk analysis per FDA guidance "
            "on PCCP for AI/ML-based SaMD."
        )


# ---------------------------------------------------------------------------
# ISO42001Exporter — ISO/IEC 42001:2023 AI Management System
# ---------------------------------------------------------------------------

# Mapping of ISO 42001 clause numbers to control narratives
_ISO42001_CONTROLS: dict[str, dict[str, str]] = {
    "6.1": {
        "title": "Actions to address risks and opportunities",
        "narrative": (
            "NovaFabric captures every AI agent run as a signed capsule. "
            "Risk assessments are conducted at promotion time via Rego policy gates. "
            "Evidence of gate evaluation is included in the Evidence Bundle."
        ),
    },
    "6.2": {
        "title": "AI system objectives and planning",
        "narrative": (
            "Objectives are defined per asset in the registry (asset_name, version, "
            "task_type). Capsule metadata records actual vs. expected behaviour."
        ),
    },
    "8.1": {
        "title": "Operational planning and control",
        "narrative": (
            "Runs are captured deterministically. Capsules include tool-permission "
            "events, redaction proof, and OTel GenAI spans. Replay modes (forensic, "
            "mocked, semantic) allow operational verification."
        ),
    },
    "8.2": {
        "title": "AI risk assessment process",
        "narrative": (
            "Maker-checker approval enforces separation of duties for production "
            "promotion (ADR-0058). NovaSeal provides cryptographic non-repudiation."
        ),
    },
    "8.3": {
        "title": "AI risk treatment",
        "narrative": (
            "WORM storage adapters (S3, Azure, GCS) enforce immutability of evidence. "
            "Secret scanning and PII redaction are applied before archival."
        ),
    },
    "9.1": {
        "title": "Monitoring, measurement, analysis and evaluation",
        "narrative": (
            "Eval suites (GAIA, SWE-bench, AgentBench, MMLU, Smoke) are run at "
            "promotion time. Scores are stored in the capsule and compared against "
            "regression thresholds via Rego policy."
        ),
    },
    "9.2": {
        "title": "Internal audit",
        "narrative": (
            "Lineage graph records provenance of every asset version. "
            "The Evidence Bundle ZIP provides a signed audit trail per ADR-0011."
        ),
    },
    "9.3": {
        "title": "Management review",
        "narrative": (
            "NovaFabric's Annex IV exporter (cap-002) provides management-ready "
            "documentation covering all 15 mandatory EU AI Act elements."
        ),
    },
    "10.1": {
        "title": "Continual improvement",
        "narrative": (
            "PCCP export (this module) documents planned modifications. "
            "Rollback is available via `nova rollback` for any production asset."
        ),
    },
    "10.2": {
        "title": "Nonconformity and corrective action",
        "narrative": (
            "Tool-permission denied events are captured in capsules and surfaced "
            "in NIS2 incident reports (cap-005). Corrective actions are logged "
            "against the incident identifier."
        ),
    },
}

_DEFAULT_CONTROLS = list(_ISO42001_CONTROLS.keys())


class ISO42001Exporter:
    """ISO/IEC 42001:2023 AI Management System evidence package exporter.

    Produces a ZIP containing:

    - ``iso42001-evidence.json``   — structured control-evidence mapping
    - ``control-narratives.json``  — plain-language narratives per clause
    - ``capsule-index.json``       — index of capsules in the audit period
    - ``README.txt``               — human-readable instructions

    Usage::

        exporter = ISO42001Exporter(
            data_dir=Path("capsules"),
            period_start=datetime(2026, 1, 1, tzinfo=timezone.utc),
            period_end=datetime(2026, 6, 30, tzinfo=timezone.utc),
        )
        out = exporter.export(output_path=Path("/tmp/iso42001-package.zip"))
    """

    def __init__(
        self,
        data_dir: Path,
        period_start: datetime,
        period_end: datetime,
    ) -> None:
        self.data_dir = data_dir
        self.period_start = period_start
        self.period_end = period_end

    def export(
        self,
        output_path: Path,
        controls: list[str] | None = None,
    ) -> Path:
        """Export ISO 42001 evidence package as ZIP.

        Args:
            output_path: Path to write the ZIP file.
            controls:    List of clause numbers to include (e.g. ``["6.1", "8.1"]``).
                         Defaults to all supported controls.

        Returns:
            Path to the written ZIP file.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        selected = controls if controls is not None else _DEFAULT_CONTROLS

        # Build control-evidence map
        evidence_map: dict[str, Any] = {}
        for clause in selected:
            ctrl = _ISO42001_CONTROLS.get(clause)
            if ctrl is None:
                evidence_map[clause] = {
                    "title": "Unknown clause",
                    "status": "not_mapped",
                    "narrative": "",
                    "evidence_refs": [],
                }
                continue
            evidence_map[clause] = {
                "title": ctrl["title"],
                "status": "documented",
                "narrative": ctrl["narrative"],
                "evidence_refs": self._gather_evidence_refs(clause),
            }

        # Build capsule index for the audit period
        capsule_index = self._build_capsule_index()

        # Build top-level package document
        package: dict[str, Any] = {
            "@context": "https://novafabric.dev/schemas/iso42001/v1",
            "standard": "ISO/IEC 42001:2023",
            "generated_at": _now_iso_full(),
            "audit_period": {
                "start": self.period_start.isoformat(),
                "end": self.period_end.isoformat(),
            },
            "controls": evidence_map,
            "capsule_count": len(capsule_index),
        }

        readme = (
            "ISO/IEC 42001:2023 AI Management System Evidence Package\n"
            "Generated by NovaFabric\n\n"
            "Contents:\n"
            "  iso42001-evidence.json    — Control-evidence mapping\n"
            "  control-narratives.json   — Plain-language control narratives\n"
            "  capsule-index.json        — Capsule index for audit period\n"
            "  README.txt                — This file\n\n"
            f"Audit period: {self.period_start.date()} to {self.period_end.date()}\n"
            f"Controls included: {', '.join(selected)}\n"
        )

        with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr("iso42001-evidence.json", json.dumps(package, indent=2))
            zf.writestr(
                "control-narratives.json",
                json.dumps(
                    {c: _ISO42001_CONTROLS[c] for c in selected if c in _ISO42001_CONTROLS},
                    indent=2,
                ),
            )
            zf.writestr("capsule-index.json", json.dumps(capsule_index, indent=2))
            zf.writestr("README.txt", readme)

        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _gather_evidence_refs(self, clause: str) -> list[str]:
        """Return a list of evidence references for *clause*."""
        refs: list[str] = []
        if not self.data_dir.exists():
            return refs

        # Collect capsule IDs in the audit period
        for child in sorted(self.data_dir.iterdir()):
            if not child.is_dir():
                continue
            manifest_path = child / "capsule.yaml"
            if not manifest_path.exists():
                continue
            data = yaml.safe_load(manifest_path.read_text())
            if not isinstance(data, dict):
                continue
            created_at_raw = data.get("created_at", "")
            if created_at_raw:
                try:
                    created_at = datetime.fromisoformat(
                        str(created_at_raw).replace("Z", "+00:00")
                    )
                    if self.period_start <= created_at <= self.period_end:
                        run_id = data.get("run_id", child.name)
                        refs.append(f"capsule:{run_id}")
                except ValueError:
                    pass

        return refs

    def _build_capsule_index(self) -> list[dict[str, Any]]:
        """Build an index of capsules within the audit period."""
        index: list[dict[str, Any]] = []
        if not self.data_dir.exists():
            return index

        for child in sorted(self.data_dir.iterdir()):
            if not child.is_dir():
                continue
            manifest_path = child / "capsule.yaml"
            if not manifest_path.exists():
                continue
            data = yaml.safe_load(manifest_path.read_text())
            if not isinstance(data, dict):
                continue
            created_at_raw = data.get("created_at", "")
            if created_at_raw:
                try:
                    created_at = datetime.fromisoformat(
                        str(created_at_raw).replace("Z", "+00:00")
                    )
                    if self.period_start <= created_at <= self.period_end:
                        index.append({
                            "run_id": data.get("run_id", child.name),
                            "asset_name": data.get("asset_name"),
                            "created_at": created_at.isoformat(),
                        })
                except ValueError:
                    pass

        return index
