# Copyright 2024 NovaFabric Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Compliance document renderer: JSON-LD + optional WeasyPrint PDF (cap-002).

WeasyPrint (BSD-2-Clause, Tier A under ADR-0024) is an optional dependency.
Install with: ``pip install 'novafabric[compliance]'``
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from .models import AnnexIVDocument, AnnexIVElement

if TYPE_CHECKING:
    pass

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>EU AI Act Annex IV — Technical Documentation</title>
<style>
  body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
          font-size: 11pt; color: #1a1a1a; margin: 2cm; }}
  h1   {{ font-size: 16pt; color: #003087; border-bottom: 2px solid #003087;
          padding-bottom: 4pt; }}
  h2   {{ font-size: 13pt; color: #003087; margin-top: 18pt; }}
  .meta {{ font-size: 9pt; color: #555; margin-bottom: 12pt; }}
  .element {{ border: 1px solid #ccc; border-radius: 4px;
              padding: 10pt; margin-bottom: 10pt; page-break-inside: avoid; }}
  .element-header {{ display: flex; justify-content: space-between;
                     align-items: baseline; }}
  .element-id {{ font-weight: bold; color: #003087; }}
  .badge {{ font-size: 8pt; padding: 2pt 6pt; border-radius: 10pt;
             font-weight: bold; }}
  .badge-complete {{ background: #d4edda; color: #155724; }}
  .badge-partial   {{ background: #fff3cd; color: #856404; }}
  .badge-missing   {{ background: #f8d7da; color: #721c24; }}
  .content {{ margin-top: 6pt; white-space: pre-wrap; font-size: 10pt; }}
  .evidence-refs {{ margin-top: 4pt; font-size: 9pt; color: #555; }}
  .method {{ font-size: 9pt; color: #888; }}
  footer {{ margin-top: 24pt; font-size: 8pt; color: #999; text-align: center;
            border-top: 1px solid #eee; padding-top: 6pt; }}
</style>
</head>
<body>
<h1>EU AI Act — Annex IV Technical Documentation</h1>
<div class="meta">
  <strong>Deployment ID:</strong> {deployment_id}<br/>
  <strong>Generated at:</strong> {generated_at}<br/>
  <strong>Schema:</strong> {schema_ref}
</div>

<h2>Summary</h2>
<table style="border-collapse:collapse; width:100%; font-size:10pt;">
<tr style="background:#f0f4ff;">
  <th style="text-align:left;padding:4pt 8pt;border:1px solid #ccc;">#</th>
  <th style="text-align:left;padding:4pt 8pt;border:1px solid #ccc;">Element</th>
  <th style="text-align:left;padding:4pt 8pt;border:1px solid #ccc;">Method</th>
  <th style="text-align:left;padding:4pt 8pt;border:1px solid #ccc;">Status</th>
</tr>
{summary_rows}
</table>

<h2>Elements</h2>
{element_blocks}

<footer>Generated by NovaFabric compliance exporter — novafabric[compliance]</footer>
</body>
</html>
"""

_SUMMARY_ROW_TEMPLATE = """<tr>
  <td style="padding:4pt 8pt;border:1px solid #ccc;">{id}</td>
  <td style="padding:4pt 8pt;border:1px solid #ccc;">{title}</td>
  <td style="padding:4pt 8pt;border:1px solid #ccc;">{method}</td>
  <td style="padding:4pt 8pt;border:1px solid #ccc;">
    <span class="badge badge-{status}">{status}</span>
  </td>
</tr>"""

_ELEMENT_BLOCK_TEMPLATE = """<div class="element">
  <div class="element-header">
    <span class="element-id">§{id} {title}</span>
    <span class="badge badge-{status}">{status}</span>
  </div>
  <div class="method">Population method: {method}</div>
  {provenance_html}
  <div class="content">{content}</div>
  {evidence_html}
</div>"""

_EVIDENCE_HTML = """<div class="evidence-refs">Evidence refs: {refs}</div>"""
_PROVENANCE_HTML = (
    """<div class="method">Provenance (ADR-0197): {source}{ref}</div>"""
)


def _provenance_html(element: "AnnexIVElement") -> str:
    """Render the ADR-0197 evidence_source marker, if present."""
    if element.evidence_source is None:
        return ""
    ref = ""
    if element.evidence_ref is not None:
        ref = f" — {element.evidence_ref.content_digest}"
    return _PROVENANCE_HTML.format(source=element.evidence_source.value, ref=ref)


def _render_html(document: AnnexIVDocument) -> str:
    """Render the AnnexIVDocument to an HTML string."""
    summary_rows = "\n".join(
        _SUMMARY_ROW_TEMPLATE.format(
            id=e.element_id,
            title=e.element_title,
            method=e.population_method,
            status=e.completeness_flag,
        )
        for e in document.elements
    )

    element_blocks = "\n".join(
        _ELEMENT_BLOCK_TEMPLATE.format(
            id=e.element_id,
            title=e.element_title,
            status=e.completeness_flag,
            method=e.population_method,
            provenance_html=_provenance_html(e),
            content=e.content or "(not available)",
            evidence_html=(
                _EVIDENCE_HTML.format(refs=", ".join(e.evidence_refs))
                if e.evidence_refs
                else ""
            ),
        )
        for e in document.elements
    )

    return _HTML_TEMPLATE.format(
        deployment_id=document.deployment_id,
        generated_at=document.generated_at,
        schema_ref=document.schema_ref,
        summary_rows=summary_rows,
        element_blocks=element_blocks,
    )


class DocumentRenderer:
    """Render compliance documents to JSON-LD and optionally PDF.

    PDF generation uses WeasyPrint (BSD-2-Clause, Tier A under ADR-0024).
    WeasyPrint is an optional dependency — a clear error is raised if not installed.

    Install with: ``pip install 'novafabric[compliance]'``
    """

    def render(
        self,
        document: AnnexIVDocument,
        output_dir: Path,
        *,
        pdf: bool = False,
    ) -> tuple[Path, Path | None]:
        """Render *document* to *output_dir*.

        Args:
            document: The :class:`AnnexIVDocument` to render.
            output_dir: Directory to write output files into (created if needed).
            pdf: If ``True``, also render a WeasyPrint PDF.

        Returns:
            ``(json_ld_path, pdf_path)`` — *pdf_path* is ``None`` if ``pdf=False``.

        Raises:
            ImportError: If ``pdf=True`` and WeasyPrint is not installed.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        safe_name = document.deployment_id.replace("/", "_").replace("\\", "_")

        # --- JSON-LD ---
        json_ld = {
            "@context": document.context,
            "@type": document.document_type,
            **document.model_dump(
                exclude={"context", "document_type"},
                mode="json",
            ),
        }
        json_ld_path = output_dir / f"annex-iv-{safe_name}.jsonld"
        json_ld_path.write_text(
            json.dumps(json_ld, indent=2, ensure_ascii=False), encoding="utf-8"
        )

        if not pdf:
            return json_ld_path, None

        # --- PDF (WeasyPrint, lazy import) ---
        try:
            from weasyprint import HTML
        except ImportError as exc:
            raise ImportError(
                "WeasyPrint is not installed.  "
                "Install it with: pip install 'novafabric[compliance]'  "
                "(or directly: pip install weasyprint>=60.0)"
            ) from exc

        html_str = _render_html(document)
        pdf_path = output_dir / f"annex-iv-{safe_name}.pdf"
        HTML(string=html_str).write_pdf(str(pdf_path))
        return json_ld_path, pdf_path
